#!/usr/bin/env python3
"""PreToolUse safety guard for Clubs 2.0.

Rationale: a push to `master` auto-deploys to production (Coolify), and the
stack runs a live PostgreSQL. This hook is a backstop that blocks a small set
of irreversible actions in-session, complementing gitleaks (which only guards
commits, not in-session edits) and the secret-scan CI.

Contract: reads the PreToolUse JSON payload on stdin. Exit 0 = allow,
exit 2 = block (stderr is shown to Claude). Fails OPEN on any internal error —
a broken guard must never freeze normal work.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys


def main() -> None:
    try:
        event = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # unparseable payload: do not interfere

    tool = event.get("tool_name", "")
    tool_input = event.get("tool_input", {}) or {}

    try:
        if tool == "Bash":
            reason = bash_violation(tool_input.get("command", "") or "")
        elif tool in ("Write", "Edit", "MultiEdit"):
            reason = path_violation(tool_input.get("file_path", "") or "")
        else:
            reason = None
    except Exception:
        sys.exit(0)  # guard bug must not block the user

    if reason:
        print(f"BLOCKED by safety-guard: {reason}", file=sys.stderr)
        sys.exit(2)
    sys.exit(0)


def bash_violation(cmd: str) -> str | None:
    # Recursive force delete (rm -rf, rm -fr, rm -r -f, --recursive --force)
    if re.search(r"(^|\s|;|&&|\|)\s*rm\s", cmd):
        has_r = bool(re.search(r"(^|\s)-\w*r", cmd, re.IGNORECASE)) or "--recursive" in cmd
        has_f = bool(re.search(r"(^|\s)-\w*f", cmd, re.IGNORECASE)) or "--force" in cmd
        if has_r and has_f:
            return "recursive force delete (rm -rf)"

    # Force-push that rewrites a protected branch's history (= prod history)
    if re.search(r"\bgit\s+push\b", cmd) and re.search(r"(--force\b|--force-with-lease\b|(^|\s)-f\b)", cmd):
        if re.search(r"\b(master|main)\b", cmd):
            return "force push to a protected branch (master/main)"
        if not re.search(r"\borigin\s+\S+", cmd) and current_branch() in ("master", "main"):
            # bare `git push --force` while standing on master
            return "force push while on a protected branch (master/main)"

    # Destructive SQL run from the shell (psql -c, etc.)
    if re.search(r"\b(DROP|TRUNCATE)\s+TABLE\b", cmd, re.IGNORECASE):
        return "destructive SQL (DROP/TRUNCATE TABLE)"
    if re.search(r"\bDROP\s+DATABASE\b", cmd, re.IGNORECASE):
        return "destructive SQL (DROP DATABASE)"

    # Piping a remote script straight into a shell (violates security.md)
    if re.search(r"\b(curl|wget)\b[^|]*\|\s*(sudo\s+)?(bash|sh|zsh)\b", cmd):
        return "piping a remote script into a shell (curl|bash)"

    return None


def path_violation(path: str) -> str | None:
    if not path:
        return None
    name = path.rsplit("/", 1)[-1]

    # Real secret env files — but .env.example/.sample/.template are committed placeholders
    if re.match(r"^\.env(\..+)?$", name) and not re.match(r"^\.env\.(example|sample|template|dist)$", name):
        return "secret env file (.env)"

    # Private keys / certificates / keystores
    if re.search(r"\.(pem|key|p12|pfx|keystore|jks)$", name) or name in ("id_rsa", "id_ed25519"):
        return "private key / certificate"

    # Dependency lock files are regenerated by the package manager, never hand-edited
    if name in ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "gradle.lockfile"):
        return "dependency lock file (regenerate via the package manager, do not hand-edit)"

    # Anything under a secrets/ directory
    if re.search(r"(^|/)secrets?/", path):
        return "secrets directory"

    return None


def current_branch() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, timeout=3,
        )
        return out.stdout.strip()
    except Exception:
        return ""


if __name__ == "__main__":
    main()
